### ISSUE TITLE
source tarball is incomplete

### ISSUE THREAD

**Issue by themaddoctor** [quackle/quackle#105]
After retrying to download the source file (v1.0.4.tar.gz) for hours with many timeouts, I finally
received the "'v1.0.4.tar.gz' saved [30647488]" message. However, it is still incomplete:
```
gzip --test -v v1.0.4.tar.gz
v1.0.4.tar.gz:
gzip: v1.0.4.tar.gz: unexpected end of file
```

**Comment by jfultz** [comment]
I don't create the source tarball.  GitHub automatically creates the `.tar.gz` and `.zip` archives advertised in the release downloads. Furthermore, I (just now) downloaded the `.tar.gz` file from the current release and ran your test, and it worked fine.

Whatever problem you're having, it's not a Quackle bug, and it's not something that is even in my power to fix.  It's happening somewhere between GitHub and your machine.

**Comment by themaddoctor** [comment]
You are correct. Thank you.
