### ISSUE TITLE
Incorrect Lexicon Word Count When Quackle is Run in a Non Admin Account in Windows

### ISSUE THREAD

**Issue by AntonyNderitu** [quackle/quackle#127]
The above issue was observed in windows 10 x64 when setting up Quackle on a client pc on a standard user account. In this case csw21 would report a word count of 281,698 on an admin account, but 279,*** on a standard account. The solution was to set Quackle to run as Administrator.

Please assist to resolve issue.

**Comment by jfultz** [comment]
The copy of CSW21 I received from Collins (which I haven't updated the repo with yet) reports the following information:
Word count: 279,077

> 2s:     127	6s:   22957	10s:   37196	14s:    9396
> 3s:    1340	7s:   34254	11s:   29010	15s:    5925
> 4s:    5620	8s:   42089	12s:   21016	
> 5s:   12915	9s:   42890	13s:   14342	
> 
> Lexicon hash: 3724aee7

This is consistent with information I see on the web, which reports that CSW21 is CSW19 with 419 words struck (279,496 - 419 = 279,077).

So, what you're reporting in Administrator mode is what sounds wrong to me, assuming that you're importing a correct word list.

Screenshots or copy/paste of the text you're seeing the "Configure Lexicon" dialog appreciated.  Everything inside of the "Lexicon Information" box should be selectable and copyable.

**Comment by AntonyNderitu** [comment]
![Screenshot (13)](https://user-images.githubusercontent.com/7792955/199376119-c2803234-1cf9-43b9-9455-4c180e2643a8.png)
After a fresh install I was able to get the right word count. I have provided a screenshot.
All is well now. Thank you very much.
