### ISSUE TITLE
Quackle's GADDAG plays words in reverse in new game adaptation

### ISSUE THREAD

**Issue by starfish1900** [quackle/quackle#129]
Hello Team Quackle
First of all I want to salute you for the extraordinary piece of software that you blessed the world of word games with. 
I am currently programming an AI bot for a new original word game named freeword and we have translated Quackle's GADDAG code in C#. But to our surprise, we noticed that the words (in green in the attached picture) are played in reverse order (bottom to top and right to left). Here is for instance the code for my GaddagNode class (I compared the code for gordongoon, gordongen and gordongenerate and it's virtually identical to Quackle cpp code save for a few stylistic differences between cpp and csharp).
public class GaddagNode
    {
        public int ithis;
        public byte[] data = new byte[4];
        public GaddagNode() { }

        public GaddagNode FirstChild(List<GaddagNode> nodes)
        {
            int p =((data[0] << 16) + (data[1] << 8) + (data[2]));

            if (p == 0)
            {
                return null;
            }
            else
            {
                return nodes[ithis + p]; 
            }

        }

        public char Letter()
        {
            return (char)(data[3] & 0x3F);
        }

        public bool IsTerminal()
        {
            return (data[3] & 0x40) != 0;
        }

        public GaddagNode NextSibling(List<GaddagNode> nodes)
        {
            if ((data[3] & 0x80) != 0)
            {
                return null;
            }
            else
            {
                return nodes[ithis + 1];
            }
        }

        public GaddagNode Child(char l, List<GaddagNode> nodes)
        {
            for (GaddagNode child = FirstChild(nodes); child != null; child = child.NextSibling(nodes))
            {
                if (child.Letter() == l)
                {
                    return child;
                }
                else if (l != 0 && child.Letter() > l)
                {
                    return null;
                }
            }
            return null;
        }
    }
I will be very delighted if you can pinpoint what we are doing wrong. Thanks for your time.
![QUACKLE_GADDAG_IN_NEW_WORD_GAME](https://github.com/quackle/quackle/assets/79879645/3c21d86c-c674-40f3-bf88-a2d5e469fda7)

**Comment by maliberty** [comment]
Can you demonstrate this happening in Quackle?  I've never noticed it and suspect you might have a translation error.

**Comment by starfish1900** [comment]
I am sorry if my post wasn't clear enough. I wasn't insinuating that this could happen in Quackle. Quackle is fine. I was just asking if you had an idea why this would happen in our translation. I will close this issue since it is not a quackle issue per se. Thanks anyway.
