### ISSUE TITLE
End-of-game time

### ISSUE THREAD

**Issue by andy-k** [quackle/quackle#18]
A way to effect time penalties (typically but not necessarily in -10 increments)
and
A way to optionally record alongside the gcg the final time remaining on each clock at the end of the game, possibly with exact seconds and deciseconds if a digital timer was used. These two features are not necessarily to be used together: it should be possible to record an end-of-game time for a player that did not overtime and it should be possible to input an arbitrary amount of time penalty without declaring the time shown on the clock.

**Comment by jfultz** [comment]
I'm not interested in recording times (although if somebody else did a decent job and submitted a pull request, I wouldn't deny it).  As for penalties, I think this basically dupes #19 (a well-designed scoring offsetting system ought to allow you to specify that it is, e.g., at the end of the game and due to a time penalty).

**Comment by andy-k** [comment]
The motivation for this is that time penalty, just as the +2x tile adjustment, is not technically part of the same move as the outplay. If that outplay is a high-scoring nine-timer that is challenged and misscored and subsequently remains the high word of the tournament, the effective score assigned to that move will include the challenge and misscoring adjustments (#19) but exclude the tile adjustment and time penalty adjustment.

How about adding an implicit pass for both players at the end of the game after the tile adjustments (be it +2x/0 or +x/-x) and allowing this pass to be misscored (part 1) and annotated (part 2)?
