### ISSUE TITLE
How to print Quackle::Move.wordTiles() ?

### ISSUE THREAD

**Issue by alkamid** [quackle/quackle#29]
In my [fork](https://github.com/alkamid/quackle/blob/c0cbbe2ece9dccb4ea219a1d797cda2d3b7b61a1/test/testharness.cpp#L718) I'm generating the output of multiple games to calculate playability. How to simply print out the `wordTiles()` value of a move? Right now I'm doing it in a very convoluted way:

```C++
std::vector<Quackle::LetterString> bestMoves;
bestMoves.push_back(moves.front().wordTiles());
UVcout << QuackleIO::Util::qstringToString(QuackleIO::Util::letterStringToQString(bestMoves[j]));
```

Surely there is a way to do it without so much casting?

**Comment by jfultz** [comment]
QUACKLE_ALPHABET_PARAMETERS->userVisible(letterString)

returns a `UVString`.  Which is just a `std::wstring` or a `std::string`.  Utilities for handling a `UVString` are in uv.h.  This didn't take much spelunking to figure out (just look at the implementation of `letterStringToQString`).
