### ISSUE TITLE
probabilityOfDrawingFromFullBag gives wrong probabilities

### ISSUE THREAD

**Issue by theSparta** [quackle/quackle#66]
When I pass the `LetterString` "AA" to the function, `Bag::probabilityOfDrawingFromFullBag`, it converts it into the `LetterString` "FF" and returns 1 which is incorrect. If this is not a bug, how do I call this function so that it returns correct values?
@jfultz

**Comment by olaugh** [comment]
My guess is your "AA" is a regular user visible string and you need to
convert it to a LetterString with AlphabetParameters::encode
