### ISSUE TITLE
Superscrabble board and bag

### ISSUE THREAD

**Issue by amnonma** [quackle/quackle#74]
Hi,
Would be great to have an option for 21x21 Superscrabble board, as well as its 200 tile bag.
Even without that, would be good for current version to allow more than 100 tiles to be played without flagging errors.
Thx,
Amnon Meyers

**Comment by jfultz** [comment]
Quackle already support (actually requires) customizing the board.  And it supports boards of up to 40x40.  So there's nothing to do there...it already works.

What's missing is an easy way to customize the tile set.  Tiles can be customized, but you have to know the kung fu to do it right, and it can't be done directly from the GUI.  But that issue has already been filed, #30.  So, closing this as a duplicate.
