### ISSUE TITLE
gaddag doesn't exist

### ISSUE THREAD

**Issue by martindemello** [quackle/quackle#78]
I checked out and compiled quackle, and it fails to start:

```
$ ./quacker/Quackle 
qt5ct: using qt5ct plugin
qt5ct: D-Bus global menu: no
Gaddag for lexicon 'csw15' does not exist.
```

At this point it just sits there - as far as I can tell it's not trying to create the gaddag, but it doesn't exit either (as per gdb it's just spinning the qteventloop and waiting for something to happen).

Also there are no instructions on how to create the missing gaddag.

**Comment by jfultz** [comment]
It doesn't have anything to do with the gaddag.  That's just an informational message and definitely not fatal (and it's created in the Settings tab, listed as the button "Build lexicon database...").

So, the core problem is, it doesn't start.  I need more info.

* Linux distro and version?
* Compiler version?
* Qt version?
* Also, where did you get Qt?  E.g., if you installed it via package manager, which one, and from which package repository?

**Comment by martindemello** [comment]
Distro: Antergos (archlinux derivative, no version since it's rolling release, but everything's up to date)

Kernel: Linux lspace 4.20.1-arch1-1-ARCH #1 SMP PREEMPT Wed Jan 9 20:25:43 UTC 2019 x86_64 GNU/Linux

Qt version 5.12, installed from the package manager (standard arch package repository)

gcc -v:
```
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp --enable-cet=auto
Thread model: posix
gcc version 8.2.1 20181127 (GCC) 
```

**Comment by martindemello** [comment]
after the latest set of system updates it's working again.
