### ISSUE TITLE
No Qt Platform Plugin Could be Initialized

### ISSUE THREAD

**Issue by Stumpy12992** [quackle/quackle#86]
Installed Quackle 1.0.4 and when I click to run, it gives a "This application failed to start because no Qt platform plugin could be initialized. Reinstalling...."

I did a reinstall but to no avail. Platform: Windows 10 Enterprise 64 bit

Quackle 1.0.3 works fine

**Comment by jfultz** [comment]
As I think is generally known by now, I fixed this in my latest upload (but another upload is coming soon to fix just a few more problems).
