### ISSUE TITLE
Word edit

### ISSUE THREAD

**Issue by brcwayne** [quackle/quackle#95]
some words are not listed and some words which suggested from championship player are not listed in game dictionary. 
Could we add or remove words?

**Comment by jfultz** [comment]
Yes, it's possible to add words to the dictionary...just edit it and select a word list to merge into it.  Are you claiming that one of the existing dictionaries is wrong?  You didn't say which dictionary you're using or give any examples of the problems you're seeing.  Until you do that, there's not much I can do with this report.

**Comment by brcwayne** [comment]
i made a dictionary when i have to add or remove the word i open the txt file add or remove the word than 
go settings  
edit lexicon 
delete lexicon 
add words from file 
choose the txt file and save but i have to reboot game. 

[tdk6.txt](https://github.com/quackle/quackle/files/3591593/tdk6.txt)

**Comment by jfultz** [comment]
Quackle only supports adding words to an existing word list, not removing them.  But you can also create a brand new dictionary from scratch if you have the entire word list.

I'm not seeing anything in this report that suggests there's an actionable bug or suggestion here, so I'm closing.

**Comment by jfultz** [comment]
Oh, and the presumption is that the text file will be UTF-8 encoded (the file you attached appears to be UTF-16 LE-encoded).

**Comment by brcwayne** [comment]
![Screen Shot 2019-09-09 at 20 26 50](https://user-images.githubusercontent.com/49405091/64552659-55a8bc00-d340-11e9-8343-4698547c7dc4.png)

add word button and

![Screen Shot 2019-09-09 at 20 28 57](https://user-images.githubusercontent.com/49405091/64552775-a6201980-d340-11e9-876b-ed1ed70ea30d.png)
remove from dict check box

**Comment by jfultz** [comment]
If you want to modify the dictionary, you do it in the Lexicon settings.  The Settings tab, the Lexicon field, either Edit the lexicon or add a new Lexicon.

<img width="426" alt="screenshot_83" src="https://user-images.githubusercontent.com/1069048/64554672-7f8ebe00-d301-11e9-9bec-e1ce0153fe10.png">

I don't think that adding or removing words as part of game play is a good idea.  The assumption is that you're working with a canonical dictionary or word list, not that you're developing it in the middle of playing games.  Such a feature would make it too easy to accidentally override and mess up a canonical dictionary without having realized you've done so.

**Comment by brcwayne** [comment]
ok you right but you preserve the mess the master dic you could add an another dialog box which is save the edited dic.
this is so imported because this program work as multilingual and sometimes you cant use some words even those are in dict. 

i still think that it is necessary feature.
