### ISSUE TITLE
32-bit version of Quackle v1.0.4 for windows needed

### ISSUE THREAD

**Issue by grumpyhippo** [quackle/quackle#98]
Hi,

I was looking for a 32-bit version of Quackle (I am using Collins 2019 dictionary) and came across the note that if I needed it I should raise an issue. So I am doing just that. Could you please build the 32-bit installer for Windows?

I'd like to install it on my (very) old laptop with Windows 7.

Thank you.

**Comment by jfultz** [comment]
Duplicates #84.
